### ISSUE TITLE
Update to Null Safety?

### ISSUE THREAD

**Issue by michael-sicpa** [mingfudu/image_overlay_map#2]
Did you plan to update to be compatible with new dart versions?
Thx

**Comment by mingfudu** [comment]
try 0.0.2 please.I have already upgraded it to null safety.

**Comment by michael-sicpa** [comment]
Ok, because here:
https://pub.dev/packages/image_overlay_map
It is not tagged as Null Safety.
But great news, thanks

**Comment by mingfudu** [comment]
my mistake, i forgot to update the version code. 0.0.3 is the latest version.
